name: Build and Publish Blog to Azure Blob Storage

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: chabad360/hugo-actions@master
        with:
          buildPath: 'public'
          hugoVersion: ''
          args: ''
      - uses: bacongobbler/azure-blob-storage-upload@v1.0.0
        with:
          source_dir: public
          container_name: $web
          connection_string: ${{ secrets.ConnString }}
          extra_args: ''

