name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: chabad360/hugo-actions@master
        with:
          buildPath: 'public'
          # Use if you have a need to build the site to another directory
          hugoVersion: ''
          # Use if your site requires a specific version of Hugo
          # Append "extended_" to the begining to use Hugo Extended
          args: ''
          # Use if you want to pass some custom arguments to Hugo
